#!/usr/bin/env node
// Release manifest: a committed snapshot of every media release's assets
// (name · size · sha256). Regenerated by the sync after each publish so git
// carries an audit trail — you can see exactly what was on a release at any
// point, detect an accidental clobber/delete (diff vs the snapshot), and know
// the expected bytes for recovery.
//
//   node tools/manifest.mjs           # write tools/manifests/<book>.json
//   node tools/manifest.mjs --diff    # report drift vs the committed snapshots
//
// Deterministic (no timestamps) so a snapshot only changes when the release
// does; git provides the timestamp. Needs network; GITHUB_TOKEN optional.

import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIR = path.join(ROOT, 'tools', 'manifests');

// pure: normalize a release's assets into a stable, comparable snapshot
export function manifestObject(tag, assets){
  const norm = (assets || []).map(a => ({
    name: a.name,
    size: a.size,
    sha256: (a.digest || '').startsWith('sha256:') ? a.digest.slice('sha256:'.length) : null,
  })).sort((x, y) => x.name.localeCompare(y.name));
  return {tag, count: norm.length, assets: norm};
}

function headers(){
  const h = {'User-Agent': 'audio-book-manifest', Accept: 'application/vnd.github+json'};
  if (process.env.GITHUB_TOKEN) h.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
  return h;
}

async function fetchRelease(mediaRepo, tag){
  const res = await fetch(`https://api.github.com/repos/${mediaRepo}/releases/tags/${tag}`, {headers: headers()});
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`${tag} -> ${res.status}`);
  return res.json();
}

async function main(){
  const catalog = JSON.parse(fs.readFileSync(path.join(ROOT, 'catalog.json'), 'utf8'));
  const diff = process.argv.includes('--diff');
  fs.mkdirSync(DIR, {recursive: true});
  let drift = 0, wrote = 0;
  for (const b of catalog.books){
    const rel = await fetchRelease(catalog.mediaRepo, b.releaseTag);
    if (!rel){ continue; }
    const man = manifestObject(b.releaseTag, rel.assets);
    const out = path.join(DIR, `${b.slug}.json`);
    const next = JSON.stringify(man, null, 2) + '\n';
    const cur = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
    if (diff){
      if (cur !== next){ drift++; console.log(`  drift: ${b.slug} (${man.count} assets now)`); }
    } else if (cur !== next){
      fs.writeFileSync(out, next);
      wrote++;
      console.log(`  wrote ${b.slug}.json (${man.count} assets)`);
    }
  }
  if (diff){
    console.log(drift ? `\n  ${drift} release(s) differ from the committed manifest.` : '  manifests match the live releases. ✓');
    process.exit(drift ? 1 : 0);
  }
  console.log(wrote ? `\n  updated ${wrote} manifest(s).` : '  manifests already current.');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url))
  main().catch(e => { console.error(e.message || e); process.exit(1); });
