#!/usr/bin/env node
// Generate STATUS.md — the whole library's fill state at a glance, so you can
// see what's published vs pending without opening the player or the tool.
// Regenerated by the sync workflow after every publish; also runnable by hand:
//
//   node tools/status.mjs            # write STATUS.md
//   node tools/status.mjs --check    # exit 1 if STATUS.md is stale (CI use)

import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {referencedAssets} from './lib-catalog.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

export function statusMarkdown(catalog){
  const lines = [];
  lines.push('# Library status', '');
  lines.push('_Generated by `tools/status.mjs` — do not edit by hand; the sync workflow rewrites it._', '');

  let totAudio = 0, totCh = 0;
  const rows = [];
  for (const b of [...catalog.books].sort((a, z) => (a.order || 99) - (z.order || 99))){
    const chs = b.chapters || [];
    const withAudio = chs.filter(c => c.audio).length;
    const withSlides = chs.filter(c => (c.slides || []).length).length;
    const extras = (b.extras || []).length;
    totAudio += withAudio; totCh += chs.length;
    const published = b.readUrl ? 'published' : 'coming soon';
    rows.push(`| ${b.title || b.slug} | ${published} | ${chs.length ? `${withAudio}/${chs.length}` : '—'} | ${chs.length ? `${withSlides}/${chs.length}` : '—'} | ${extras || '—'} |`);
  }
  lines.push('| Book | State | Audio | Slides | Extras |', '|---|---|---|---|---|', ...rows, '');
  lines.push(`**${totAudio}/${totCh} chapters have audio** across ${catalog.books.length} books · ` +
             `${referencedAssets(catalog).length} media assets served.`, '');

  // per-book chapter detail
  for (const b of [...catalog.books].sort((a, z) => (a.order || 99) - (z.order || 99))){
    const chs = b.chapters || [];
    if (!chs.length) continue;
    lines.push(`## ${b.title || b.slug}`, '', '| # | Chapter | Audio | Slides |', '|--:|---|---|---|');
    for (const c of chs){
      const a = c.audio ? fmt(c.audio.duration) : '·';
      const nImg = (c.slides || []).filter(s => s.type === 'image').length;
      const pdf = (c.slides || []).some(s => s.type === 'pdf');
      const sl = nImg ? `${nImg} pages` : (pdf ? 'pdf' : '·');
      lines.push(`| ${c.n} | ${c.title} | ${a} | ${sl} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function fmt(s){
  if (!s) return '✓';
  s = Math.round(s);
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;
}

// CLI
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)){
  const catalog = JSON.parse(fs.readFileSync(path.join(ROOT, 'catalog.json'), 'utf8'));
  const md = statusMarkdown(catalog) + '\n';
  const out = path.join(ROOT, 'STATUS.md');
  if (process.argv.includes('--check')){
    const cur = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
    if (cur !== md){
      console.error('STATUS.md is stale — run `node tools/status.mjs` and commit.');
      process.exit(1);
    }
    console.log('STATUS.md is current. ✓');
  } else {
    fs.writeFileSync(out, md);
    console.log(`wrote ${out}`);
  }
}
